liip_search:
    path: /search
    defaults: { _controller: liip_search.google:searchAction }

liip_searchbox:
    path: /searchbox
    defaults: {_controller: liip_search_default_controller:showSearchBoxAction}

liip_search_paging:
    path: /_searchpaging
    defaults: {_controller: liip_search_default_controller:showPagingAction}